### ISSUE TITLE
What version of OpenAI is currently used?

### ISSUE THREAD

**Issue by lindseylubin** [liffiton/Gen-Ed#1]
Have all the files been updated to support openai 1.12.0? If not what version works with Gen-Ed currently?

**Comment by liffiton** [comment]
I wrote it before OpenAI released version 1.0 of their library, and it still [requires a pre-1.0 version](https://github.com/liffiton/Gen-Ed/blob/a408cb4148acb75e7769c44a9cf5c542e6d1304e/pyproject.toml#L32).  I plan to update it to use the latest `openai` release when I get some time.

**Comment by lindseylubin** [comment]
I see, that resolved my errors. Thank you!

**Comment by liffiton** [comment]
Great!  Also, running `pip -e .` or `pip -e .[test]` should install all the dependencies with the correct versions automatically.  If you run into trouble with that or anything else, just let me know!
