### ISSUE TITLE
Responses contain LaTeX equations in text format

### ISSUE THREAD

**Issue by umar221b** [liffiton/Gen-Ed#6]
One of my students received a response that contains LaTeX in text format:

<img width="1148" alt="Screenshot 2024-11-09 at 8 50 54 PM" src="https://github.com/user-attachments/assets/4972282b-1fa4-47c5-96b3-abbb2f724858">

It looks like ChatGPT uses [Katex](https://katex.org/) to typeset mathematical equations after it generates them. I wonder if something similar is possible here.

Happy to play around with the idea and try to come up with a PR.

**Comment by liffiton** [comment]
Thanks for the suggestion!  I've also seen a few responses with tex formulas here and there.  They're rare, but adding mathjax or katex to render them shouldn't be too hard and is probably worth the added weight.  I'll figure out how best to fit that into the application (though I appreciate the offer to make a PR).

**Comment by liffiton** [comment]
Should be fixed now.  Let me know if you spot any problems with it.  And thanks again for the nudge!

**Comment by umar221b** [comment]
Works wonderfully. Thanks a lot for the quick fix!
